export const items = eternalVar("items") ?? $$([
	{
		id: "0",
		title: "Hannibal",
		genre: "Crime, Drama, Horror",
		year_from: 2013,
		year_to: 2015, 
		runtime: 42,
		country: "United States",
		language: "English",
		total_seasons: 3,
		seasons: [true, true, true],
		mark: "f",
		finished: false,
	},
	{
		id: "1",
		title: "Supernatural",
		genre: "Fantasy, Drama, Horror",
		year_from: 2005,
		year_to: 2020, 
		runtime: 42,
		country: "United States",
		language: "English",
		total_seasons: 15,
		seasons: [true, true, false, true, true, true, true, true, false, false, false, false, false, false, false],
		mark: "f",
		finished: false,
	}
]);